name: hki_quality
description: "HKI QUALITY."
publish_to: 'none' 
version: 1.0.0+1
environment:
  sdk: '3.2.3'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  get: 4.6.6
  dotted_border: ^2.1.0
  intl: ^0.19.0
  flutter_launcher_icons: ^0.13.1

dev_dependencies:
  flutter_lints: ^3.0.1
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/image/
flutter_launcher_icons:
  android: "launcher_icons"
  ios: true
  image_path: 'assets/image/splash.png'
  min_sdk_android: 21
